### ISSUE TITLE
SimpleCov mal configurado

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#101]
![image](https://user-images.githubusercontent.com/19597045/32548690-b2b21f1a-c46d-11e7-8da1-4ae62e1170f6.png)
¯\_(ツ)_/¯Sei que negócio é esse não. ¯\_(ツ)_/¯

**Comment by MatheusRich** [comment]
Resolvido no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/102

**Comment by MatheusRich** [comment]
Resolvido no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/102
