### ISSUE TITLE
Arrumar criação de componentes(@another) em testes de Releases, Revisions e Stories.

### ISSUE THREAD

**Issue by Matheus456** [fga-gpp-mds/2017.2-Grupo8#110]
**Comportamento Esperado:** @another_project, @another_release e outros com id respectivo do @another_user, @another_project... 
**Comportamento Encontrado:** @another_project, @another_release e outros com id respectivo do @user, @project...

Os "anothers" objetos que estão sendo testados estão sendo criados com id de outro objetos. 

Como está:
    @another_release = Release.create(
      name: "Real Madrid",
      description: "Descriptions",
      initial_date: "01/01/2018",
      final_date: "01/01/2019",
      amount_of_sprints: "20",
      project_id: @project.id
    )

Como deveria ser:
    @another_release = Release.create(
      name: "Real Madrid",
      description: "Descriptions",
      initial_date: "01/01/2018",
      final_date: "01/01/2019",
      amount_of_sprints: "20",
      project_id: @another_project.id
    )

**Comment by MatheusRich** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/116
