### ISSUE TITLE
US08 - Visualizar Burndown

### ISSUE THREAD

**Issue by pedrokelvin** [fga-gpp-mds/2017.2-Grupo8#113]
Eu como usuário desejo visualizar o Burndown de uma sprint com objetivo de acompanhar o desenvolvimento da sprint. 

*Critérios de Aceitação*
- [x] Criar um método que retorne um JSON com as informações necessárias para criar o burndown, datas e pontos queimados.

**Comment by MatheusRich** [comment]
Resolvida no PR #134
