### ISSUE TITLE
US16 - Alocar História para Sprint

### ISSUE THREAD

**Issue by pedrokelvin** [fga-gpp-mds/2017.2-Grupo8#114]
Eu como usuário desejo alocar histórias para uma sprint com objetivo de gerenciar as atividades que serão realizadas durante esse período. 

*Critérios de Aceitação*
- [ ] Mover uma Issue do Backlog para a Sprint e transformar em História
- [ ] Histórias não terminadas na Sprint anterior tem que voltar para o Backlog.

**Comment by MatheusRich** [comment]
Resolvida no PR #127
