### ISSUE TITLE
Validar dependências de datas

### ISSUE THREAD

**Issue by Matheus456** [fga-gpp-mds/2017.2-Grupo8#120]
Data de história precisa estar dentro de uma sprint , data de início e fim uma sprint não pode estar contido no intervalo de duração de outra e a data de uma release não pode coincidir com a data de outra.

**Comment by cantuariavc** [comment]
Resolvido no pull request #122

**Comment by Matheus456** [comment]
Não, ainda não foi resolvida. Eu dei um close no pull porque eu precisava arrumar algumas coisas ainda, por causa dos testes.

**Comment by cantuariavc** [comment]
Podia ter deixado aberto. Era só colocar um comentário lá.

**Comment by cantuariavc** [comment]
Resolvido no pull request #124
