### ISSUE TITLE
Não se pode deixar criar uma sprint com data antes ou depois da data da release

### ISSUE THREAD

**Issue by ThalissonMelo** [fga-gpp-mds/2017.2-Grupo8#123]
Atualmente é possível criar uma release em uma data e encaixar sprints dentro dessa release com uma data q não bate com a data da release

**Comment by Matheus456** [comment]
Mandei o pull request #124, mas linkei a issue #120 que era a mesma coisa.

**Comment by MatheusRich** [comment]
Issue duplicada. Ver #120
