### ISSUE TITLE
Revogar a autorização do Falko no GitHub por api

### ISSUE THREAD

**Issue by cantuariavc** [fga-gpp-mds/2017.2-Grupo8#137]

**Comment by alaxalves** [comment]
@cantuariavc Poderia descrever melhor o que ta acontecendo?

**Comment by cantuariavc** [comment]
Eu e nem o @ThalissonMelo encontramos um modo de mandar um revoke para o GitHub através de api sem ter que mandar a senha do usuário, @alaxalves.

**Comment by alaxalves** [comment]
Então vou fechar essa issue. @cantuariavc ;)
