### ISSUE TITLE
US 18 - Manter Feature

### ISSUE THREAD

**Issue by MateusO97** [fga-gpp-mds/2017.2-Grupo8#144]
## Comportamento esperado

O sistema deve apresentar, criar, editar e excluir Features

## Critérios de Aceitação

- [ ] Front End completo.
- [ ] Back End completo.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
I think this feature is not necessary anymore.
