### ISSUE TITLE
US01 - Pesquisar Projeto

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#15]
Eu, como usuário, desejo pesquisar um projeto, com o objetivo de facilitar a localização deste.

**Critérios de Aceitação**
- [x] Dado que o usuário informe uma string contida num nome de um projeto existente, o sistema deve retornar todos os projetos com a string contida.  
- [x] Dado que o usuário informe uma string não contida num nome de um projeto existente, o sistema deve retornar uma mensagem de aviso.

_Tasks_

- [x] BackEnd
- [x] FrontEnd

**Comment by matheussbernardo** [comment]
Já Mergada!
