### ISSUE TITLE
Issues devem ter model?

### ISSUE THREAD

**Issue by MartinsLucas** [fga-gpp-mds/2017.2-Grupo8#155]
## Comportamento esperado

A classe issue não manipula o banco de dados, portanto, teoricamente, não deveria ter models, migrations, etc.

## *Comportamento atual

Atualmente existe uma model da classe Issues, assim como migrations e arquivos associados. Deve-se estudar se estes arquivos são usados em algum lugar do código, e se não, excluí-los do código.

**Comment by alaxalves** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/175

**Comment by alaxalves** [comment]
Realmente vimos q não havia a necessidade dessa model
