### ISSUE TITLE
US 19 - Visualizar Velocity

### ISSUE THREAD

**Issue by Matheus456** [fga-gpp-mds/2017.2-Grupo8#156]
## Comportamento esperado

Enviar dados adequados para o front criar o gráfico do velocity.

## *Comportamento atual

O Falko não possui velociry.

## *Passos para reproduzir o comportamento

Em caso de bugs, cite quais passos foram executados para chegar no problema.

## **Critérios de Aceitação

 [X]Back End completo.

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by MatheusRich** [comment]
Resolvida no PR #154
