### ISSUE TITLE
Linkar conta com o github não funciona em prod

### ISSUE THREAD

**Issue by matheussbernardo** [fga-gpp-mds/2017.2-Grupo8#157]
## Comportamento esperado

O sistema deveria linkar ao github tanto em producao como em desenvolvimento

## *Comportamento atual

Linkar so funciona em ambiente de dev

## *Passos para reproduzir o comportamento

Tentar linkar com o github em prod nao funciona

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by alaxalves** [comment]
Acredito que seja o mesmo problema da issue #195

**Comment by alaxalves** [comment]
@matheussbernardo Acho que isso tem a ver com o endpoint configurado no app 'Falko' do GitHub

**Comment by alaxalves** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/198
