### ISSUE TITLE
US03 - Conectar Conta do Github

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#16]
Eu, como usuário, desejo conectar minha conta ao Github, com o objetivo de de importar meus repositórios.

*Critérios de Aceitação*
- [x] Linkar com conta e a partir desse momento poder fazer requisicoes para a API do github

*Tasks*

- [x] FrontEnd
- [x] BackEnd 17/10

**Comment by matheussbernardo** [comment]
Já mergada.
