### ISSUE TITLE
US21 - Manter Nota

### ISSUE THREAD

**Issue by MateusO97** [fga-gpp-mds/2017.2-Grupo8#163]
## Comportamento esperado

O usuário deve ser capaz de visualizar a nota de seu projeto de acordo com a ponderação das métricas que considerar mais importante

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.
- [ ] Usuário inserir o peso das métricas.
- [ ] Sistema apresentar a nota do projeto.
- [ ] Usuário editar o peso das notas.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
Resolvida no PR #175
