### ISSUE TITLE
US 17- Manter Épico

### ISSUE THREAD

**Issue by Matheus456** [fga-gpp-mds/2017.2-Grupo8#164]
## Comportamento esperado

O sistema deve ser capaz de criar um épico.

## *Comportamento atual

Descreva como o sistema se comporta atualmente.

## *Passos para reproduzir o comportamento

Em caso de bugs, cite quais passos foram executados para chegar no problema.

## **Critérios de Aceitação

- [ ] BackEnd Completo
- [ ] FrontEnd completo

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [ ] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by MatheusRich** [comment]
I think this feature is not necessary anymore.
