### ISSUE TITLE
Mudar render do JSON do Burndown para Array

### ISSUE THREAD

**Issue by MateusO97** [fga-gpp-mds/2017.2-Grupo8#166]
## Comportamento esperado

O sistema deve retornar um array como JSON para utilizar no ChartJS

## Comportamento atual

O sistema retorna o JSON como uma Hash.

## Critérios de Aceitação

Retornar JSON como um array.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

## Prints:
Comportamento atual:
![json_hash](https://user-images.githubusercontent.com/27258892/33605920-c609e724-d9a2-11e7-81bb-b30ec42fb484.png)

**Comment by alaxalves** [comment]
Resolvida no PR #167

**Comment by MateusO97** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/167
