### ISSUE TITLE
Seed não está criando um projeto

### ISSUE THREAD

**Issue by ThalissonMelo** [fga-gpp-mds/2017.2-Grupo8#171]
## Comportamento esperado

O sistema deve criar dois projetos

## *Comportamento atual

O sistema está criando só um

## *Passos para reproduzir o comportamento

Rode o seed

## **Critérios de Aceitação

Criar os dois projetos ao rodar o seed

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
Resolvida no PR #172
