### ISSUE TITLE
Excluir GPA 

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#176]
## Comportamento esperado

Deve-se remover tudo relacionado à GPA, pois não há mais suporte a essa métrica. 

## Comportamento atual

Código inútil no software. 

## Passos para reproduzir o comportamento

Nenhum 

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
Resolvida no PR #187
