### ISSUE TITLE
Consertar kanban de alocar stories para sprints

### ISSUE THREAD

**Issue by ThalissonMelo** [fga-gpp-mds/2017.2-Grupo8#177]
## Comportamento esperado

Alocar corretament

## *Comportamento atual

Não está alocando

## *Passos para reproduzir o comportamento

Tente alocar

## **Critérios de Aceitação

Alocar

## Checklist

- [x] A issue possui nome significativo.

*Exclua caso a issue seja uma história

**Comment by alaxalves** [comment]
Resolvida no PR #178
