### ISSUE TITLE
US10 - Manter Sprints

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#18]
Eu, como usuário, desejo gerenciar sprints com objetivo de melhorar a organização do desenvolvimento do projeto

*Critérios de Aceitação*
- Sprints devem ser criadas à partir de datas (início e fim);
- Sprints devem ter uma descrição opcional.
- Sprints devem vir com um nome padrão, mas editável se o usuário desejar;

- [x] CRUD Completo

**Comment by matheussbernardo** [comment]
Já mergada!
