### ISSUE TITLE
US14 - Manter História

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#19]
Eu, como usuário, desejo manter uma issue, com o objetivo de gerenciar os problemas presentes em um projeto.

*Critérios de Aceitação*

- O usuário deve ter a conta sincronizada com o github para criar histórias;
- O usuário deve estar logado para gerenciar informações das histórias;
- O usuário deverá visualizar a história com todas suas informações.

- [ ] CRUD Completo

**Comment by fabiolamfleury** [comment]
Testes:

- [ ] Criação de issue no github a partir de uma história introduzida no falko (verificar se ela também é criada no backlog*).

- [ ] Tentativa de criação de uma história sem estar logado, deve impedir e comunicar o usuário.

- [ ] Tentativa de criação de uma história sem estar sincronizado com o github, deve impedir e comunicar o usuário.

- [ ] Alteração das informações da issue de forma adequada quando o usuário possui a conta sincronizada.

- [ ] Tentativa de atualização de uma história sem estar logado, deve impedir e comunicar o usuário.

- [ ] Tentativa de atualização de uma história sem estar sincronizado com o github, deve impedir e comunicar o usuário.

- [ ] Visualização das informações da issue de forma adequada quando o usuário possui a conta sincronizada.

- [ ] Tentativa de visualização de uma história sem estar logado, deve impedir e comunicar o usuário.

- [ ] Tentativa de visualização de uma história sem estar sincronizado com o github, deve impedir e comunicar o usuário.

- [ ] Exclusão da história caso o usuário tenha permissão (esteja logado e possua a conta sincronizada)

- [ ] Tentativa de exclusão de uma história sem estar logado, deve impedir e comunicar o usuário.

- [ ] Tentativa de exclusão de uma história sem estar sincronizado com o github, deve impedir e comunicar o usuário.
