### ISSUE TITLE
BackEnd quebrado em homolog

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#191]
## Comportamento esperado

Ambiente deveria estar funcionando.

## *Comportamento atual

BackEnd está down.

## *Passos para reproduzir o comportamento

Requests não funcionam em homolog.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/33901632-8efe9a10-df59-11e7-8370-706acdc87f52.png)

**Comment by MatheusRich** [comment]
Resolvida no PR #192
