### ISSUE TITLE
Adicionar assignees nos parametros de retorno de issue

### ISSUE THREAD

**Issue by ThalissonMelo** [fga-gpp-mds/2017.2-Grupo8#193]
## Comportamento esperado

O sistema deve retornar os assignees quando realizada uma requisição

## *Comportamento atual

O sistema não lista assignees

## **Critérios de Aceitação

O sistema retornar os assignees nas issues

## Checklist

- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
Resolvida no PR #194
