### ISSUE TITLE
Aumentar cobertura de testes existentes

### ISSUE THREAD

**Issue by drianne** [fga-gpp-mds/2017.2-Grupo8#201]
## Comportamento esperado

Aumento de cobertura de teste de alguns arquivos .

## *Comportamento atual

Cobertura de 90%

## *Passos para reproduzir o comportamento
Rodar testes no backEnd

## **Critérios de Aceitação
Aumento da cobertura

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by alaxalves** [comment]
Resolvida no PR #202
