### ISSUE TITLE
Traduzir Repositório

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#208]
## Comportamento esperado

Read Me, Templates, documentos de configuração todos estão em português. Acredito que deveríamos traduzi-los todos para ingles para internacionalizar o respositório.

## Critérios de Aceitação
Traduzir:
- [x] Read Me
- [x] Template de Issue
- [x] Template de Pr
- [x] Instalação do Docker

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
Queira que passassemos a usar o ingles nas issues, nos comentarios, em qualquer lugar do repo. O que acha @MatheusRich ?

**Comment by MatheusRich** [comment]
@alaxalves Essa é a ideia. Só estamos usando português nos locais onde não está traduzido ainda. Acredito que algum templates eu já traduzi no front-end. Falta trazer pra cá e adaptar o necessário.

**Comment by alaxalves** [comment]
@MatheusRich No repo do front-end também deve ser mudado então.
