### ISSUE TITLE
Atualizar docker para utilizar ruby 2.4.4

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#218]
## Comportamento esperado

Imagem docker deve usar ruby-2.4.4

## *Comportamento atual

Imagem docker usa ruby-2.4.1

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by pvsousalima** [comment]
Apenas um update na imagem Docker é necessaria?

**Comment by MartinsLucas** [comment]
> Apenas um update na imagem Docker é necessaria?

Olá @pvsousalima. Não exatamente. O Dockerfile deve ser alterado, e os eventuais problemas resultantes da atualização do Ruby devem ser corrigidos. Não será possível atualizar a imagem, mas a atualização da versão no Dockerfile já é suficiente.

**Comment by pvsousalima** [comment]
Blz! Pegarei essa issue para fazer @MartinsLucas 👍

**Comment by alaxalves** [comment]
Not required for now.
