### ISSUE TITLE
Criar `Makefile` pra facilitar execução de comandos

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#224]
## Comportamento esperado

`Makefile` contendo abstrações de comandos `docker`

## *Comportamento atual

Não possui Makefile

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
Solved at #226
