### ISSUE TITLE
Travis PR build "endless"

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#231]
## Expected Behaviour 

When travis build is in devel or master branch, it gets "endless" because the registered IPs there doesn't exist anymore.

## *Current Beahaviour

Endless builds

## *Steps to reproduce unexpected behaviour

Just commit in master or devel, or open a PR.

## Checklist

- [x] Issue has labels.
- [x] Issue has screenshots if required.
- [x] Issue has an significant name.

![image](https://user-images.githubusercontent.com/19597045/40273586-0edbf5aa-5b99-11e8-94cf-84fd2e751175.png)

**Comment by henriquepjv** [comment]
Boa tarde pessoal, posso pegar essa tarefa?
