### ISSUE TITLE
Travis using unwanted language

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#240]
## * **Expected Behaviour 

Travis should use `language: generic` instead

## * **Current Behaviour

![image](https://user-images.githubusercontent.com/19597045/41983648-258403ee-7a05-11e8-927d-1d6f740e664d.png)

## Checklist

- [x] Issue has labels.
- [x] Issue has screenshots if required.
- [x] Issue has a significant name.

**Comment by MatheusRich** [comment]
@alaxalves Why?

**Comment by alaxalves** [comment]
@MatheusRich because it pre-bundles the dependencies, but since we use docker there there's no need to it. Actually it makes our builds slower.
