### ISSUE TITLE
US12 - Manter Retrospectiva de Sprint

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#31]
Eu, como usuário, desejo manter uma retrospectiva de sprint, com o objetivo de avaliar os acontecimentos desta e propor melhorias.

**Critérios de Aceitação**
- Não é necessário fazer a retrospectiva para criar uma nova sprint
- Utilizar checklists (Pontos negativos e Melhorias)
- Atrelada à uma sprint

*Tasks*
- [x] Back End
- [x] Front End

**Comment by fabiolamfleury** [comment]
Testes:

- [x] Criação de Retrospectiva de sprint finalizada
  Caso a sprint esteja finalizada, a retrospectiva deve ser criada e o usuário comunicado.

- [x] Criação de Retrospectiva de sprint finalizada sem estar logado
  Caso a sprint esteja finalizada, e um usuário não logado tentar criar uma retrospectiva, impedi-lo.

- [x] Criação de Retrospectiva de sprint em andamento 
 Caso a sprint ainda esteja em andamento, não pode ser permitido a criação da retrospectiva e o usuário deve ser notificado.

- [ ] Criação de Retrospectiva de sprint inexistente
Na tentativa de cadastro de uma retrospectiva com uma sprint nula, deve-se impedir e comunicar o usuário.

- [x] Criação de Retrospectiva de sprint sendo que já existe retrospectiva daquela sprint
Caso tente-se criar uma retrospectiva sendo que já existe uma retrospectiva daquela sprint, deve-se impedir e comunicar o usuário

- [x] Deletar retrospectiva de sprint com sucesso
Deletar a retrospectiva da sprint de um gerente logado e ter a resposta do usuário.

- [x] Deletar retrospectiva de sprint sem usuário logado
Na tentativa de deletar sem estar logado, impedir e comunicar ao usuário

- [x] Editar a retrospectiva de sprint alterando algum dos campos
Alterar os dados salvos e comunicar ao usuário

- [ ] Editar a retrospectiva de sprint deixando todos os campos em branco
Impedir que o usuário deixe todos os campos em branco ao alterar a retrospectiva e comunicá-lo.
