### ISSUE TITLE
Criar Helpers pra melhorar o CodeClimate

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#35]
- Criar helpers pra evitar a duplicação de código

![image](https://user-images.githubusercontent.com/19597045/31838382-52439e44-b5bb-11e7-9951-131f988c89f6.png)

**Comment by matheussbernardo** [comment]
@alaxalves Qual seria a duplicação? Essa issue é boa para o pessoal de mds.

**Comment by danieloda** [comment]
https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/47
