### ISSUE TITLE
US05 - Listar Possíveis Projetos

### ISSUE THREAD

**Issue by MateusO97** [fga-gpp-mds/2017.2-Grupo8#38]
Eu, como usuário, desejo visualizar repositórios existentes na minha conta do github, com o objetivo de importar seus dados para o Falko.

*Critérios de Aceitação*
- Listar repositórios do usuário e de suas organizações 
- Importar múltiplos repositórios
- Exibir separadamente repositórios do usuário e repositórios das suas organizações                                 - - Botão de importar no AddProject para usuários linkados

**Comment by fabiolamfleury** [comment]
Testes:

- [ ] Listar repositórios de usuário logado

- [ ] Tentativa de listar repositórios de usuário não logado, mensagem de erro

- [ ] Listar repositórios do usuário e das organizações que ele está

- [ ] Listar repositórios do usuário somente quando ele não possui organizações

**Comment by cantuariavc** [comment]
#50
