### ISSUE TITLE
Container do Postgres está cacheando 'Data' desatualizado

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#40]
O container do pg nao reconhece a base previamente criada.

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/31918096-a8776392-b839-11e7-8ee0-9d18cc929a3d.png)

**Comment by alaxalves** [comment]
Alguem poderia por favor apagar e clonar o repo pra ver se o problema persiste no pc de vcs tb??

**Comment by cantuariavc** [comment]
![captura de tela 2017-10-24 as 15 13 47](https://user-images.githubusercontent.com/21143590/31957848-c2802568-b8ce-11e7-9b34-7b9d1ee7bad9.png)

**Comment by cantuariavc** [comment]
Está dando, às vezes, esse erro agora.

**Comment by alaxalves** [comment]
Como está o seu docker-compose.yml quando aparece esse erro??

**Comment by alaxalves** [comment]
Essa issue é com relação ao BackEnd @cantuariavc

**Comment by cantuariavc** [comment]
#44
