### ISSUE TITLE
Criar email da organização

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#78]
!!!!!Necessário pro Código de Conduta!!!!!!

**Comment by Matheus456** [comment]
Criei o email, convidei todos do grupo e coloquei na Wiki, não sei se está no lugar certo. Está na home, no final da página.

**Comment by alaxalves** [comment]
Boa! Era isso mesmo. Meu email aparece como maintainer de altas coisas. Vou dividir esse peso com vcs, ja q nao fiz as coisas sozinho kkk
