### ISSUE TITLE
US06 - Designar Membro

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#84]
Eu, como usuário, desejo designar um ou mais membros à uma história, com o objetivo de rastrear o desenvolvimento.

**Critérios de Aceitação**
- [x] Listar apenas colaboradores do projeto.

*Tasks*
- [x] Backend

**Comment by alaxalves** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/109
