### ISSUE TITLE
US22 - Manter Issue

### ISSUE THREAD

**Issue by MartinsLucas** [fga-gpp-mds/2017.2-Grupo8#85]
Eu, como usuário, desejo gerenciar as _issues_ do GitHub nos repositórios dos meus projetos com o objetivo de promover a rastreabilidade das atividades.

Critérios de Aceitação

* As Issues devem ser criadas, editadas e fechadas no GitHub
* As Issues gerenciadas devem pertencer a um repositório do GitHub importado para o Falko

Tasks
- [X] BackEnd
- [ ] FrontEnd

**Comment by MatheusRich** [comment]
BackEnd concluído no PR https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/pull/86
