### ISSUE TITLE
Atributo check_project ainda é retornado nas requisições

### ISSUE THREAD

**Issue by MatheusRich** [fga-gpp-mds/2017.2-Grupo8#97]
Apesar da migração ter sido excluída, o atributo ainda é retornado pela API.

![image](https://user-images.githubusercontent.com/20938712/32523029-cb96113e-c400-11e7-8049-2964e642b58b.png)

**Comment by cantuariavc** [comment]
![whatsapp image 2017-11-07 at 22 38 53](https://user-images.githubusercontent.com/21143590/32548157-d82bc266-c46b-11e7-9ebe-8751be291e17.jpeg)
![whatsapp image 2017-11-07 at 22 42 33](https://user-images.githubusercontent.com/21143590/32548159-d848e9ea-c46b-11e7-8007-6c84e6126187.jpeg)
![whatsapp image 2017-11-07 at 22 43 38](https://user-images.githubusercontent.com/21143590/32548160-d864aab8-c46b-11e7-9b56-174b7fa70470.jpeg)

**Comment by cantuariavc** [comment]
No meu está normal.

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/32548494-f5d4feb2-c46c-11e7-9596-0aa8a86b5212.png)
Também testei e tá normal, acho que o seu banco devia ter usuários pré-criados que já possuiam esse atributo. Vou fechar essa issue.
